### PR TITLE
Feature/stable request response macro (squashed commit)

### PR DESCRIPTION
**Pull request by dozed**
For details see #511

### CODE REVIEW

**Comment by dozed** [comment]
There is still a problem with `ScalatraAtmosphereHandler`. I need to take a look at this over the weekend.

**Comment by seratch** [comment]
@dozed Thanks. But unfortunately Travis CI builds failed. Please check when you have time.

**Comment by dozed** [comment]
There was a problem in scalatra-atmosphere. There were no request/response objects available (in the ThreadLocal):

- when an `AtmosphereClient` is constructed due to a GET request
- when an `AtmosphereClient.receive` is run due to an incoming message

This lead to null pointers when trying to access them in HttpServletRequestReadOnly and AtmosphereClient.receive.

I needed to pass the `ScalatraBase` to `ScalatraAtmosphereHandler` and then use the `withRequestResponse` to put the request/response in scope. `AtmosphereClient` provides now request/response methods similar to `AsyncResult`/`StableResult`.

Also `withRequestResponse` and `withRouteMultiParams` are now package-protected.

**Comment by seratch** [comment]
Thanks.

>Also withRequestResponse and withRouteMultiParams are now package-protected.

Changing these scope in 2.4 can be acceptable for existing users.

**Pull request merged**
