### PR TITLE
Swagger 2.0 support

### PR DESCRIPTION
**Pull request by takezoe**
This generates Swagger 2.0 JSON from existing metadata of Swagger support in Scalatra. You have to modify only the Swagger version defined in metadata "2.0" as follows:

``` scala
class IndexSwagger extends Swagger("2.0", "1", ApiInfo(
  title = "Swagger Sample App",
  description = "This is a sample server Petstore server.  You can find out more about Swagger \n    at <a href=\"http://swagger.wordnik.com\">http://swagger.wordnik.com</a> or on irc.freenode.net, #swagger.",
  termsOfServiceUrl = "http://helloreverb.com/terms/",
  contact = "apiteam@wordnik.com",
  license = "Apache 2.0",
  licenseUrl = "http://www.apache.org/licenses/LICENSE-2.0.html"
))
```

Generated Swagger 2.0 JSON example is here: https://github.com/takezoe/scalatra/blob/topic/swagger-2.0/swagger/src/test/resources/swagger.json

### CODE REVIEW

**Comment by takezoe** [comment]
Original issue is #495.

**Comment by rossabaker** [comment]
I am barely doing any Swagger, so this is hard for me to review well.  It looks reasonable to me.  Since nobody else has spoken up, I think the best way might be to merge it and get people using it in the real world.

**Comment by seratch** [comment]
@rossabaker I agree. I think it's fine to merge this. Let's merge this after waiting for comments from others for a few days.

**Comment by momania** [comment]
Can you please update JodaTime in this pull request and make the `isDate` check, check for `LocalDate`, rather than the deprecated `DateMidnight` ?
https://github.com/scalatra/scalatra/blob/2.4.x/swagger/src/main/scala/org/scalatra/swagger/Swagger.scala#L370

**Comment by seratch** [comment]
@takezoe Is it possible to work on the @momania 's request above?

**Comment by takezoe** [comment]
@seratch Pushed fix for `DateMidnight `.  I would like to update library versions including JodaTime for Scalatra 2.5 in the branch for Scala 2.12.

**Comment by ygrene-austin** [comment]
👍

**Comment by salceson** [comment]
What is the status of this PR? Can we perhaps merge this soon?

**Comment by seratch** [comment]
Ah, right. I think this PR is ready to be merged. @takezoe thx for your great work 👍

**Comment by iamalto** [comment]
i did as mentioned above to generate Swagger json spec for 2.0. The json generated is fine and is already in version 2.0 but the UI rendered seemed to look different. I would like the endpoints to be grouped by controller. it used to work before i changed to 2.0 but now, all the endpoints are shown together under "default". Can someone guide me through.

**Comment by jleider** [comment]
Trying to update to swagger 2.0 and am experiencing the same issue as @iamalto. Anyone have any solutions?

**Comment by takezoe** [comment]
@iamalto @jleider Use `tags` which was added in Scalatra 2.5.1 (https://github.com/scalatra/scalatra/pull/647) to group operations.

**Pull request merged**
