### PR TITLE
Deprecate RicherString#isBlank

### PR DESCRIPTION
**Pull request by magnolia-k**
and added openjdk11 to .travis.yml

Although there is a possibility of further review in the future, I decided to go through the test first.

### CODE REVIEW

**Comment by takezoe** [comment]
In my opinion, such abuse of extension for fundamental classes like String is not good idea. My idea is marking existing methods as deprecated and modify existing code to not use them. How do you think about it? Is this idea unrealistic...?

**Comment by magnolia-k** [comment]
@takezoe 

Please review.

---

I rebuilt PR

https://github.com/scalatra/scalatra/pull/879

Since every use of `isBlank` was not appropriate, 
replaced it with another method.

`blankOption` and `nonBlank` are using too many places, we only replace the implementation with Apache Common.

This is the test with openjdk 11.

**Comment by takezoe** [comment]
Can we close this pull request if #879 is merged?

**Comment by magnolia-k** [comment]
@takezoe 
yes!

**Pull request closed without merging**
