### PR TITLE
Add a Gitter chat badge to README.markdown

### PR DESCRIPTION
**Pull request by gitter-badger**
### scalatra/scalatra now has a Chat Room on Gitter

@dozed has just created a chat room. You can visit it here: [https://gitter.im/scalatra/scalatra](https://gitter.im/scalatra/scalatra?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.markdown:

[Gitter](https://gitter.im/scalatra/scalatra?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by dozed** [comment]
Oha, what did I do?! Do we want that?

**Comment by seratch** [comment]
Currently we have #scalatra channel on the Freenode IRC. http://www.scalatra.org/community/index.html
But I think it's also fine to use gitter as a place for Scalatra community. My projects are using gitter for casual Q&A like [this](https://gitter.im/scalikejdbc/en). gitter is nice and handy.

**Comment by rossabaker** [comment]
I created a room for http4s just to see what Gitter was all about.  Without
advertising it, we've had users show up there that didn't know about our
IRC.  We've talked about eventually making it the primary chat room on
http4s.  (A bug in the IRC bridge, where it stops syncing after a while, is
the only thing holding me back.)  I'm not opposed to making it a secondary
channel for Scalatra, and maybe eventually migrating there as the primary
chat room.

**Comment by seratch** [comment]
I just add a link to gitter as secondary chat. http://scalatra.org/community/index.html

**Comment by rossabaker** [comment]
My previous comment about the IRC bridge has been fixed.   I wouldn't be opposed to making Gitter the primary support channel.  What do others think?

**Pull request merged**
