### PR TITLE
#473 Support parameter values containing semicolon

### PR DESCRIPTION
**Pull request by eudactus**
This fixes issue #473

### CODE REVIEW

**Comment by jakehoward** [comment]
Hi, 

Can anyone help me by letting me know if this PR is likely to be accepted and if so roughly how long it would be until it's merged in?

A task we're looking to do is dependent on this and it would be good to know if we should wait/park the task/look at other options. 

Thanks very much in advance :)

**Comment by rossabaker** [comment]
I'm sorry.  I somehow overlooked this one.

The current path pattern parser was tested to be fully compatible with Sinatra.  This changes that behavior, although I do see the use case for it.  I wonder if we could make this configurable somehow to both scratch your itch and maintain compatibility with old Scalatra apps and direct ports from old Sinatra apps?

**Comment by eudactus** [comment]
Hi Ross, thanks for looking into this. Given that the build passed, presumably there is no test that covers the sinatra-like behaviour you describe. What kind of behaviour would this pull request break?

**Comment by takezoe** [comment]
Fixed in #691

**Pull request closed without merging**
