### PR TITLE
deleted dependency on scalatra-json

### PR DESCRIPTION
**Pull request by magnolia-k**
It depends on Scalatra-json to use parseOpt which is a method of json4s,
but it depends only on json4s...

### CODE REVIEW

**Comment by takezoe** [comment]
Does this mean that it requires json4s-jackson in user projects? (even if they want to use json4s-native)

**Comment by magnolia-k** [comment]
No, Just 4s Jackson and Native can still be selected for user code. I use Jackson in the test code, but even if I rewrite it to Native, the test will go through.

**Comment by magnolia-k** [comment]
Originally scalatra-atmosphere depends on json4s-jackson, but it can not be deleted from scalatra-atmosphere, but it is ok if you add it to depend on user code side only.

**Comment by takezoe** [comment]
> Originally scalatra-atmosphere depends on json4s-jackson, but it can not be deleted from scalatra-atmosphere

Ah... I see... It's not good, but I understood that the situation doesn't become worse.

**Pull request merged**
