### PR TITLE
Scalatra Swagger: Add "java.time.Instant" to the list of supported DateTime types

### PR DESCRIPTION
**Pull request by taryk**
...and also test all other supported DateTime types

### CODE REVIEW

**Comment by takezoe** [comment]
@taryk Thanks! Do you need a new version of `2.6.x` immediately?

**Comment by takezoe** [comment]
@taryk 2.6.4 has been released: https://github.com/scalatra/scalatra/tree/v2.6.4

**Comment by takezoe** [comment]
@taryk Could you also send pull request to `2.7.x` branch because it's our current active branch? Even if you don't want to do it by yourself, we can do it instead (will cherrypick if it's possible).

**Comment by taryk** [comment]
@takezoe Good point! I'll see if I can do the same in `2.7.x` later today.

**Comment by taryk** [comment]
@takezoe Raised one into `2.7.x` - https://github.com/scalatra/scalatra/pull/871

**Pull request merged**
