### PR TITLE
Convert RicherString to implicit value class

### PR DESCRIPTION
**Pull request by olandere**
This commit changes RicherString to take advantage of the implicit classes and value classes added in Scala 2.10.  The advantage to this is that the compiler can eliminate the wrapper class and basically do a method call on a static object which is faster than instantiating the wrapper and calling a method on it.  Since RicherString is now an implicit value class, these are not allowed by the compiler to be top-level classes, so it was moved into the org.scalatra.util package object.  Users of RicherString no longer need to explicitly import it, instead just import the package object.  

Note that this is a breaking change - external code with explicit dependencies on RicherString would need updated to use the package object.

### CODE REVIEW

**Comment by seratch** [comment]
>Note that this is a breaking change - external code with explicit dependencies on RicherString would need updated to use the package object.

Is there any idea to keep backwards compatibility?

**Comment by xuwei-k** [comment]
I think there is no ways keep backwards **binary** compatibility.
but maybe we can keep **source** compatibility [this way](https://github.com/xuwei-k/scalatra/commit/87e283d997c114)

**Comment by rossabaker** [comment]
We generally strive for source compatibility in minor versions and binary compatibility in major versions.  I like @xuwei-k's idea.

**Comment by olandere** [comment]
Yeah - I went a little overboard. The change @xuwei-k proposes is certainly safer and you get the perf increase by making it a value class.  The additional change making it an implicit class cleans the code up a little, but certainly is not necessary.  I can put together another pull req with just that change.

**Comment by seratch** [comment]
I'm afraid it's a little bit overkill that just importing `org.scalatra.util._` enables this implicit conversion for String values. How about keeping to use `org.scalatra.util.RicherString._`?

**Comment by takezoe** [comment]
Close this request because I created new one against 2.6.0. See #682.

**Pull request closed without merging**
