### PR TITLE
Related to #513: Discussion of Req/Resp stability

### PR DESCRIPTION
**Pull request by lloydmeta**
Related to #513

- Add a test demonstrating instability of Request (and likely Response)
- Add a proposed solution for getContextPath

### CODE REVIEW

**Comment by lloydmeta** [comment]
Related discussions on Jetty seem to say that this is "unspecified" territory in the Servlet spec so they won't fix it ( see [this thread](http://jetty.4.x6.nabble.com/jetty-users-getContextPath-returns-null-td4962387.html) and [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=433321) )

Since Scalatra is built using Scala, a lang that focuses on concurrency, and already contains ways for people to hook into that aspect of the language via `AsyncResult`, it may be a pity to ignore issues like this in this framework.

**Comment by lloydmeta** [comment]
@dozed continuing the discussion here.

The issue is that `HttpServletRequest` is an interface that gets provided by the Servlet container (could be Tomcat or Jetty or MyFavouriteContainer), meaning what gets wiped out and when is not really something we can depend on. So in essence, if we want to be safe, we would need to copy all of the gettable attributes (so far I've only demonstrated doing that with one attribute in one place). I haven't the time to go through the Servlet spec in detail, but from the discussions in Jetty (I posted links above), it looks like the Servlet API leaves a lot of holes when it comes to defining async behaviour because it was not designed from the ground up to support it in the first place.

WRT copying stuff: I'm unsure if we need to or should do the same to the HttpServletResponse too..

There's also the possibility of providing immutable versions of Servlet Responses and Requests and changing Scalatra over to providing those to the developer (a la Spray), but in my opinion, that would eliminate one of the biggest reasons people choose Scalatra over say something like Spray: it allows them to keep doing things in the "Java/Ruby-way" (mutating the request and casting..) or using Java libs that depend on certain behaviours of these Servlet interfaces.

**Comment by dozed** [comment]
Maybe we could try to make it work at least for Scalatra 2.4.x with the Servlet API and then do it properly for a Scalatra 3.x with https://github.com/http4s/http4s.

**Comment by lloydmeta** [comment]
> Maybe we could try to make it work at least for Scalatra 2.4.x with the Servlet API

Right, in 3b07113, I added stable overridden values for (what I believe to be) all the getters.

Note that things like 

```scala
override val changeSessionId: String = request.changeSessionId
```

can't be done safely (maybe there are others) because that particular one throws `llegalArgumentException` if there is no session. Who knows what other things throw exceptions in Java-land...

> then do it properly for a Scalatra 3.x

That might throw off a lot of people, but sounds like a worthwhile thing to strive for.

**Comment by rossabaker** [comment]
Yes, the plan is to put an eventual Scalatra 3.x on [http4s](/http4s/http4s) to work around these gotchas of mutability and provide an alternative runtime to servlet containers (though servlets will retain first class support).

**Comment by lloydmeta** [comment]
@rossabaker continuing discussions on possible solutions here:

> The context path might be available in a horrible, awful request attribute. I have observed different servlet containers behaving differently on the same code, but if a request value has suddenly disappeared, it may be tucked away in that request context.

> I wonder if it might help to redefine our own helpers to fall back to these request attributes on an unexpected null.

Not sure if I follow, but I tried the following:

* failed due to NPE on calling `getAsyncContext`, which actually returns not a `HttpServletRequest` but rather an instance of the parent `ServletRequest` class.

  ```scala
req.getAsyncContext.getRequest.getAttribute(AsyncContext.ASYNC_CONTEXT_PATH).toString
  ```
* failed due to NPE due to null attributes by the time the attribute is accessed asynchronously 

  ```scala
req.getAttribute(AsyncContext.ASYNC_CONTEXT_PATH).toString
  ```

**Comment by seratch** [comment]
I understand the current status on Scalatra's `AsyncResult` as below:

- Accessing HttpServletRequest object within `AsyncResult` operation doesn't work as users expect right now because they occasionally may be already recycled
- Accessing recycled objects is very dangerous (e.g. accessing other request's cookie values)
- The lifecycle of HttpServletRequest objects is uncontrollable because it depends on each Servlet container implementation

If my understanding is correct, I think the following idea can be reasonable enough. 

- Introduce `HttpServletRequestWrapper` which supports only getters for immutable values copied from the original request object only when `AsyncResult` instantiation
- Naming, just an idea: `class HttpServletRequestReadOnlyCopy extends HttpServletRequestWrapper`
- Describe the limitation of it: "it's a read-only and partial copy at some point, the `request` won't be shared access threads"

@rossabaker @dozed 
At least, that will be surely better than current status (= never working correctly). What you think?

**Comment by dozed** [comment]
There are two cases:

1. Request can be recycled (asynchronous request handling is beyond the HTTP request/response cycle)

```scala
get("/foo1") {
  Future {
    Thread.sleep(1000)
    request.getSession // IllegalStateException due to no SessionManager, request is recycled
  }
  Ok()
}
```

2. Request attributes can be recycled (when the request is put to asynchronous mode, it is passed back the Jetty's handler chain, which modifies the attributes)

```scala
get("/foo2") {
  Future {
    request.getContextPath
  }
}
```

We discussed primarily 2) here, where the the asynchronous request handling does not diverge from the HTTP request handling lifecycle.

> If my understanding is correct, I think the following idea can be reasonable enough.

+1 from me.

We also need to think about the response.

**Comment by lloydmeta** [comment]
> What you think?

> +1 from me.

:+1:  from me as well → done in 2d658b6

> We also need to think about the response

Indeed, according to [this blog post](http://petercipov.com/not-only-servlet/) and [this info page from IBM](http://www-01.ibm.com/support/knowledgecenter/SSAW57_7.0.0/com.ibm.websphere.nd.doc/info/ae/ae/rweb_servlet_pooling.html), response objects *also* get recycled "for performance".  Although I'm unsure what to do there, because we do need to mutate the response at some point..

**Comment by lloydmeta** [comment]
Hi guys,

I added a test to see if request values get leaked between requests in cdccdea.
    
The idea is to increase the chances of a request handler thread and its accompanying request object getting recycled and thus handling multiple request before the worker app threads get to work on the request.
    
So, Client threads >> Jetty Http handler threads >> worker threads
    
For some reason, it looks like request values *do not* get mixed up, even though it seems like the should. I know we should be happy about this, but since I don't know the reason why, I'm wondering if my test is flawed..

**Comment by seratch** [comment]
I misunderstood about this and this is a good news. Thanks. 

This pull request already improves much about `request` within `AsyncResult`. But I'm still not sure what and how we should care about `response`... Any thoughts?

**Comment by seratch** [comment]
@dozed @rossabaker 

>This pull request already improves much about request within AsyncResult. But I'm still not sure what and how we should care about response... Any thoughts?

IMO, when the `response` is already recycled, the current thread within the `AsyncResult` can do nothing against the main thread's response because the response was actually sent to the client. 

So I think there is no more things to do about `response` at least in this pull request. Please correct me if I'm wrong. If my understanding is correct, I'd like to merge this pull request within days.

**Comment by dozed** [comment]
We could provide similar guarantees for a response. That way we dont rely on implementation details of a servlet container (for performance or whatever reasons). So what about creating a partial snapshot of a response using a `HttpServletResponseWrapper` too?

**Comment by lloydmeta** [comment]
> There seem to be only five attributes affected by partial recycling during a dispatch in Jetty 

That's Jetty ;) The problem is that there are other servlet containers. Unless the Servlet spec restricts recycling to those 5, or you keep track of the code in each of the popular containers (dunno which ones Scalatra promises to be compatible with, but off the top of my head, JBoss, Jetty, Tomcat, Glassfish, Websphere ....), I think it's better to be safe than sorry.

**Comment by rossabaker** [comment]
In practice, I have heard of one Websphere user, and everyone else uses
either Jetty or Tomcat.  I'm sure there are others quietly using others.
Still, I hope we don't rule out any Servlet 3.0+ containers.

**Comment by lloydmeta** [comment]
Interesting :) when I used to deal with Servlets the only containers we used were JBoss and Glassfish! I guess times have changed.

**Comment by dozed** [comment]
I think it's better to be safe than sorry.

I see your point. Although I would prefer to have some real evidence, I am also fine with the current version.

+1 from me

**Comment by seratch** [comment]
Now we can merge this PR. Thank you all.

**Pull request merged**
