### PR TITLE
StableResult macro fixes

### PR DESCRIPTION
**Pull request by dozed**
This patch fixes a few problems

- Handle action results of type Nothing (see below)
- Handle owner chain bug
  - use a multi-level macro approach
  - untypechecking does not work, since trees are already transformed and cant be typed later correctly (see https://gist.github.com/dozed/d49ee979dc657f5a8829, https://github.com/scalatra/scalatra/issues/527)
  - transformation needs to type the subtrees (`typingTransform`)
- Macro hygiene (see http://docs.scala-lang.org/overviews/quasiquotes/hygiene.html)
  - use fully qualified type names, e.g. `_root_.org.scalatra.Route` instead of `Route`
      - does not require imports at the callsite
      - generated code refers to correct symbols
  - invoke methods from `ScalatraBase` (**TODO**)

--------

Details for Nothing issue: Actions returning Nothing, e.g. when using halt(). Nothing conforms to all types and also to StableResult/AsyncResult. This lead to an expression of type Nothing not being wrapped in a StableResult.

Example:

```scala
notFound {
  halt(404, <h1>Not found.</h1>)
}
```

Was rewritten to:

```scala
doNotFound = (() => StableResultServlet.this.halt[scala.xml.Elem](scala.this.Predef.int2Integer(404), {
  {
    new scala.xml.Elem(null, "h1", scala.xml.Null, scala.this.xml.TopScope, false, ({
      val $buf: scala.xml.NodeBuffer = new scala.xml.NodeBuffer();
      $buf.&+(new scala.xml.Text("Not found."));
      $buf
    }: _*))
  }
}, StableResultServlet.this.halt$default$3[Nothing], StableResultServlet.this.halt$default$4[Nothing])(reflect.this.ManifestFactory.classType[scala.xml.Elem](classOf[scala.xml.Elem])))
```

It should be rewritten to:

```scala
doNotFound = (() => {
  class cls$macro$5 extends org.scalatra.StableResult {
    def <init>() = {
      super.<init>();
      ()
    };
    val is = StableResultServlet.this.halt[scala.xml.Elem](scala.this.Predef.int2Integer(404), {
      {
        new scala.xml.Elem(null, "h1", scala.xml.Null, scala.this.xml.TopScope, false, ({
          val $buf = new scala.xml.NodeBuffer();
          $buf.&+(new scala.xml.Text("Not found."));
          $buf
        }: _*))
      }
    }, StableResultServlet.this.halt$default$3[Nothing], StableResultServlet.this.halt$default$4[Nothing])(reflect.this.ManifestFactory.classType[scala.xml.Elem](classOf[scala.xml.Elem]))
  };
  val res$macro$6 = new cls$macro$5();
  res$macro$6.is
})
```

### CODE REVIEW

**Comment by seratch** [comment]
Travis build with Scala 2.10 failed. https://travis-ci.org/scalatra/scalatra/jobs/66792211

**Comment by seratch** [comment]
>use fully qualified type names, e.g. _root_.org.scalatra.Route instead of Route

I just fixed this at #526

**Comment by seratch** [comment]
@dozed Sorry, I just found you already fixed the Route issue #525 here.

But my test case at #526 seems to be better to detect similar issues. If you merge my test code into this pull request, that'll be fine too. What do you think?

**Comment by dozed** [comment]
@seratch Yes, there are two things: 1) import could be missing at call site 2) there can be a different symbol with the same name at the call site. For those two reasons we need to use the fully-qualified name.

**Comment by dozed** [comment]
In some cases untyping trees leads to incorrect code: https://gist.github.com/dozed/d49ee979dc657f5a8829

**Comment by dozed** [comment]
Here is a gist which summarizes the problems: https://gist.github.com/dozed/3321ddd519589a7b6aa6

Instead of untypechecking we can manually fix the symbol owner chain. See https://github.com/scalamacros/macrology201/commits/part1

**Pull request merged**
