### PR TITLE
Added request/response as implicits to DSL methods. Fixes #435.

### LINKED ISSUE #435: Error with FutureSupport and ScalateI18nSupport using templating
Related to my SO question: https://stackoverflow.com/questions/26423692/scalatra-i18n-with-asyncresult

Using Scalatra 2.2.2/2.3.0 I cannot get following to work using mustache or scaml:
```
class FutureController(system: ActorSystem) extends ScalatraServlet with FutureSupport with ScalateSupport with ScalateI18nSupport{

  protected implicit def executor: ExecutionContext = system.dispatcher

  get("/") {
    new AsyncResult {
      val is = Future(mustache("frontpage.mustache"))
    }
  }
}
```

The error is:
```
org.scalatra.ScalatraException: There needs to be a request in scope to call messages
```

### PR DESCRIPTION
**Pull request by dozed**
Some DSL methods accessed request/response directly, which made them not safe with multi-threading. I added request/response implicits to all DSL methods.

This fixes #435.

### CODE REVIEW

**Comment by dozed** [comment]
Running each test on its own works. I am looking into it.

**Comment by seratch** [comment]
@dozed Any update on this pull request?

**Comment by dozed** [comment]
@seratch No, I didnt have time yet.

**Comment by rossabaker** [comment]
Is this ready?  It looks ready.

**Comment by dozed** [comment]
The PR should be good to merge. The TemplateEngine is now associated to `(ServletContext.hashCode, ServletContext.contextPath)` which allows to have two ServletContexts with same path mapping in two different servlet containers in the same JVM.

**Comment by seratch** [comment]
LGTM.

**Pull request merged**
